"""OpenAI Agents SDK integration and Operations Agent coordinator.

Integrates the OpenAI Agents SDK with the deterministic workflow engine,
registering the 5 operational business tools and enforcing strict safety invariants.
"""

from datetime import datetime, timezone
import re
from typing import Any, Optional
import uuid

from agents import Agent, FunctionTool, Runner, function_tool
from pydantic import BaseModel, Field

from app.agent.instructions import OPERATIONS_AGENT_INSTRUCTIONS
from app.agent.model import ModelSettings, get_model_settings, has_api_key
from app.tools import (
    CompanyBriefOutput,
    CompanyResearchOutput,
    create_company_brief,
    create_onboarding_checklist,
    draft_welcome_email,
    record_audit_event,
    research_company,
)
from app.workflow.engine import WorkflowEngine
from app.workflow.recovery import (
    FailureCategory,
    RetryPolicy,
    classify_failure,
    failure_injector,
)
from app.workflow.state import (
    Artifact,
    ErrorRecord,
    Plan,
    Task,
    TaskStatus,
    ToolResult,
    WorkflowState,
    WorkflowStatus,
)
from app.workflow.validation import validate_task_execution


class PlannedTask(BaseModel):
    """A planned task generated by the operations agent."""

    task_id: str = Field(default_factory=lambda: f"task_{uuid.uuid4().hex[:8]}")
    name: str
    description: str = ""
    tool_name: Optional[str] = None
    depends_on: list[str] = Field(default_factory=list)
    requires_approval: bool = False

    def to_task(self) -> Task:
        """Convert planned task to an executable workflow Task."""
        return Task(
            task_id=self.task_id,
            name=self.name,
            description=self.description,
            tool_name=self.tool_name,
            depends_on=self.depends_on,
            requires_approval=self.requires_approval,
            status=TaskStatus.PENDING,
        )


class WorkflowPlan(BaseModel):
    """Structured workflow plan decomposed from a user operations request."""

    objective: str
    tasks: list[PlannedTask] = Field(default_factory=list)

    def to_plan(self) -> Plan:
        """Convert to the workflow Plan model."""
        return Plan(
            objective=self.objective,
            tasks=[t.to_task() for t in self.tasks],
        )


def get_registered_tools() -> list[FunctionTool]:
    """Return the five operational business tools wrapped as OpenAI Agents SDK FunctionTools."""
    return [
        function_tool(research_company, strict_mode=False),
        function_tool(create_company_brief, strict_mode=False),
        function_tool(create_onboarding_checklist, strict_mode=False),
        function_tool(draft_welcome_email, strict_mode=False),
        function_tool(record_audit_event, strict_mode=False),
    ]


def create_sdk_agent(
    name: str = "AIOperationsAgent",
    model: Optional[Any] = None,
    instructions: str = OPERATIONS_AGENT_INSTRUCTIONS,
    tools: Optional[list[FunctionTool]] = None,
) -> Agent:
    """Instantiate the core OpenAI Agents SDK Agent."""
    settings = get_model_settings()
    model_name_or_obj = model if model is not None else settings.model_name
    registered_tools = tools if tools is not None else get_registered_tools()

    return Agent(
        name=name,
        instructions=instructions,
        model=model_name_or_obj,
        tools=registered_tools,
    )


class OperationsAgent:
    """High-level Operations Agent coordinating AI planning with the deterministic workflow engine."""

    def __init__(
        self,
        settings: Optional[ModelSettings] = None,
        sdk_agent: Optional[Agent] = None,
        model: Optional[Any] = None,
    ) -> None:
        self.settings = settings or get_model_settings()
        self.tools = get_registered_tools()
        if sdk_agent is not None:
            self.sdk_agent = sdk_agent
        else:
            model_to_use = model if model is not None else self.settings.model_name
            self.sdk_agent = create_sdk_agent(
                model=model_to_use,
                tools=self.tools,
            )

    def run(
        self,
        request: str,
        state: Optional[WorkflowState] = None,
    ) -> WorkflowState:
        """Canonical AI Agent execution path via the OpenAI Agents SDK Runner.

        The Runner invokes the LLM, which reasons over the request and selects
        registered tools. The application intercepts the executed tool calls,
        validates results, creates artifacts, enforces approval gates, and
        records state in WorkflowEngine.

        Pipeline:
        Request -> SDK Runner -> Model -> Tool Calls -> Tools -> Tool Results -> WorkflowState
        """
        if state is None:
            state = WorkflowState(
                workflow_id=f"wf_{uuid.uuid4().hex[:8]}",
                request=request,
            )

        engine = WorkflowEngine(state)

        # Transition state: CREATED -> PLANNING
        if state.status == WorkflowStatus.CREATED:
            engine.transition_to(WorkflowStatus.PLANNING)

        # Transition state: PLANNING -> EXECUTING
        engine.transition_to(WorkflowStatus.EXECUTING)

        # Invoke the OpenAI Agents SDK Runner
        run_result = Runner.run_sync(self.sdk_agent, request)

        # Extract tool call items and their corresponding outputs from the SDK execution loop
        new_items = getattr(run_result, "new_items", [])

        tool_calls: list[Any] = [it for it in new_items if type(it).__name__ == "ToolCallItem"]
        tool_outputs: list[Any] = [it for it in new_items if type(it).__name__ == "ToolCallOutputItem"]

        # Map each tool call to its output by call_id or index
        for idx, tc in enumerate(tool_calls):
            tco = tool_outputs[idx] if idx < len(tool_outputs) else None
            tool_name = getattr(tc, "tool_name", "unknown_tool")
            task_id = f"task_{tool_name}_{idx + 1}"

            task = Task(
                task_id=task_id,
                name=f"Execute {tool_name}",
                tool_name=tool_name,
                status=TaskStatus.PENDING,
            )
            engine.add_task(task)
            engine.transition_task(task.task_id, TaskStatus.RUNNING)

            output_val = getattr(tco, "output", None) if tco else None

            is_error = isinstance(output_val, str) and (
                output_val.startswith("An error occurred") or "validation error" in output_val.lower()
            )

            if is_error or output_val is None:
                error_msg = str(output_val) if output_val else "Tool produced no output."
                category, is_retryable = classify_failure(error_msg)
                engine.add_audit_event(
                    event_type="failure_classified",
                    details={
                        "task_id": task.task_id,
                        "category": category.value,
                        "is_retryable": is_retryable,
                        "error": error_msg,
                    },
                )
                err = ErrorRecord(
                    task_id=task.task_id,
                    error_type="ToolExecutionError",
                    message=error_msg,
                    retryable=is_retryable,
                )
                engine.record_error(err)
                engine.transition_task(task.task_id, TaskStatus.FAILED)
                engine.add_audit_event(
                    event_type="task_failed",
                    details={"task_id": task.task_id, "tool": task.tool_name, "error": error_msg},
                )
                engine.block_dependent_tasks(task.task_id)
                continue

            # Handle successful output
            if hasattr(output_val, "to_tool_result"):
                tool_res = output_val.to_tool_result()
            elif hasattr(output_val, "model_dump"):
                tool_res = ToolResult(
                    tool_name=tool_name,
                    success=True,
                    data=output_val.model_dump(mode="json"),
                )
            elif isinstance(output_val, dict):
                tool_res = ToolResult(
                    tool_name=tool_name,
                    success=True,
                    data=output_val,
                )
            else:
                tool_res = ToolResult(
                    tool_name=tool_name,
                    success=True,
                    data={"raw_output": str(output_val)},
                )

            engine.record_tool_result(task.task_id, tool_res)

            # Register domain artifacts based on tool output
            if tool_name == "research_company":
                comp_name = getattr(output_val, "company_name", "Unknown")
                engine.add_artifact(
                    Artifact(
                        artifact_id=f"art_res_{uuid.uuid4().hex[:6]}",
                        artifact_type="company_research",
                        name=f"Research: {comp_name}",
                        content=getattr(output_val, "description", ""),
                    )
                )
            elif tool_name == "create_company_brief":
                brief_id = getattr(output_val, "brief_id", f"brief_{uuid.uuid4().hex[:6]}")
                comp_name = getattr(output_val, "company_name", "Unknown")
                engine.add_artifact(
                    Artifact(
                        artifact_id=brief_id,
                        artifact_type="company_brief",
                        name=f"Brief: {comp_name}",
                        content=getattr(output_val, "summary", ""),
                    )
                )
            elif tool_name == "create_onboarding_checklist":
                chk_id = getattr(output_val, "checklist_id", f"chk_{uuid.uuid4().hex[:6]}")
                items = getattr(output_val, "items", [])
                engine.add_artifact(
                    Artifact(
                        artifact_id=chk_id,
                        artifact_type="onboarding_checklist",
                        name="Onboarding Checklist",
                        content=f"{len(items)} items created",
                    )
                )
            elif tool_name == "draft_welcome_email":
                draft_id = getattr(output_val, "draft_id", f"draft_{uuid.uuid4().hex[:6]}")
                body = getattr(output_val, "body", "")
                engine.add_artifact(
                    Artifact(
                        artifact_id=draft_id,
                        artifact_type="welcome_email_draft",
                        name="Welcome Email Draft",
                        content=body,
                    )
                )

            engine.transition_task(task.task_id, TaskStatus.COMPLETED)

            # Strict Safety Gate: draft_welcome_email requires approval before delivery
            if tool_name == "draft_welcome_email":
                recipient = getattr(output_val, "recipient", "client")
                engine.request_approval(
                    action=f"Dispatch Welcome Email to {recipient}",
                    task_id=task.task_id,
                )
                # Halts execution at WAITING_FOR_APPROVAL
                break

        # Attach plan to state based on executed tasks
        state.plan = Plan(objective=request, tasks=list(state.tasks))

        # Evaluate final status deterministically
        final_status = engine.evaluate_final_status()
        if final_status != state.status:
            engine.transition_to(final_status)
            if final_status == WorkflowStatus.COMPLETED:
                engine.add_audit_event(event_type="workflow_completed", details={})
            elif final_status == WorkflowStatus.PARTIALLY_COMPLETED:
                engine.add_audit_event(
                    event_type="workflow_partially_completed",
                    details={
                        "completed_tasks": [t.task_id for t in state.tasks if t.status == TaskStatus.COMPLETED],
                        "failed_tasks": [t.task_id for t in state.tasks if t.status == TaskStatus.FAILED],
                        "blocked_tasks": [t.task_id for t in state.tasks if t.status == TaskStatus.BLOCKED],
                    },
                )
            elif final_status == WorkflowStatus.FAILED:
                engine.add_audit_event(event_type="workflow_failed", details={})

        return state

    def plan_workflow(self, request: str) -> WorkflowPlan:
        """Analyze operations request and produce a structured WorkflowPlan.

        Decomposes the primary onboarding flow:
        Research -> Brief -> Checklist -> Draft Email (with mandatory approval gate).
        """
        company_match = re.search(r"onboard\s+([A-Za-z0-9\s]+?)(?:\.|$|,)", request, re.IGNORECASE)
        company_name = company_match.group(1).strip() if company_match else "Acme Corporation"

        tasks: list[PlannedTask] = []

        t1_id = f"task_research_{uuid.uuid4().hex[:6]}"
        tasks.append(
            PlannedTask(
                task_id=t1_id,
                name=f"Research {company_name}",
                description=f"Gather operational background and verify company profile for {company_name}.",
                tool_name="research_company",
                depends_on=[],
                requires_approval=False,
            )
        )

        t2_id = f"task_brief_{uuid.uuid4().hex[:6]}"
        tasks.append(
            PlannedTask(
                task_id=t2_id,
                name=f"Prepare Company Brief for {company_name}",
                description=f"Synthesize operational brief from research findings for {company_name}.",
                tool_name="create_company_brief",
                depends_on=[t1_id],
                requires_approval=False,
            )
        )

        t3_id = f"task_checklist_{uuid.uuid4().hex[:6]}"
        tasks.append(
            PlannedTask(
                task_id=t3_id,
                name=f"Create Onboarding Checklist for {company_name}",
                description=f"Generate structured onboarding procedure checklist for {company_name}.",
                tool_name="create_onboarding_checklist",
                depends_on=[t2_id],
                requires_approval=False,
            )
        )

        t4_id = f"task_email_{uuid.uuid4().hex[:6]}"
        tasks.append(
            PlannedTask(
                task_id=t4_id,
                name=f"Draft Welcome Email for {company_name}",
                description=f"Draft operational welcome message for human review prior to release to {company_name}.",
                tool_name="draft_welcome_email",
                depends_on=[t2_id],
                requires_approval=False,
            )
        )

        return WorkflowPlan(
            objective=f"Onboard {company_name}",
            tasks=tasks,
        )

    def run_deterministic(
        self,
        request: str,
        state: Optional[WorkflowState] = None,
        company_name_override: Optional[str] = None,
    ) -> WorkflowState:
        """Deterministic execution helper bypassing LLM reasoning (for offline testing/benchmarking)."""
        plan = self.plan_workflow(request)

        if state is None:
            state = WorkflowState(
                workflow_id=f"wf_{uuid.uuid4().hex[:8]}",
                request=plan.objective,
            )

        engine = WorkflowEngine(state)

        if state.status == WorkflowStatus.CREATED:
            engine.transition_to(WorkflowStatus.PLANNING)

        engine.set_plan(plan.to_plan())
        engine.transition_to(WorkflowStatus.EXECUTING)

        last_research: Optional[CompanyResearchOutput] = None
        last_research: Optional[CompanyResearchOutput] = None
        last_brief: Optional[CompanyBriefOutput] = None
        retry_policy = RetryPolicy()

        for task in list(state.tasks):
            # Check dependency constraints: if any dependency failed/blocked, block this task
            if task.status == TaskStatus.BLOCKED or not engine.can_execute_task(task.task_id):
                if task.status != TaskStatus.BLOCKED:
                    engine.transition_task(task.task_id, TaskStatus.BLOCKED)
                    engine.add_audit_event(
                        event_type="task_blocked",
                        details={"task_id": task.task_id, "reason": "Unsatisfied upstream dependencies"},
                    )
                continue

            current_attempt = 0
            while True:
                engine.transition_task(task.task_id, TaskStatus.RUNNING)
                engine.add_audit_event(
                    event_type="task_started",
                    details={"task_id": task.task_id, "tool": task.tool_name, "attempt": current_attempt + 1},
                )

                try:
                    # Check controlled failure injection seam
                    failure_injector.check_failure(task.tool_name)

                    if task.tool_name == "research_company":
                        comp_name = company_name_override if company_name_override is not None else (
                            plan.objective.replace("Onboard", "").strip() or "Acme Corporation"
                        )
                        research_res = research_company(comp_name)
                        last_research = research_res
                        engine.record_tool_result(task.task_id, research_res.to_tool_result())
                        engine.add_artifact(
                            Artifact(
                                artifact_id=f"art_res_{uuid.uuid4().hex[:6]}",
                                artifact_type="company_research",
                                name=f"Research: {research_res.company_name}",
                                content=research_res.description,
                            )
                        )
                        engine.transition_task(task.task_id, TaskStatus.COMPLETED)
                        if task.retry_count > 0:
                            engine.add_audit_event(
                                event_type="task_retry_succeeded",
                                details={"task_id": task.task_id, "tool": task.tool_name, "retries": task.retry_count},
                            )
                        break

                    elif task.tool_name == "create_company_brief":
                        brief_res = create_company_brief(last_research)
                        last_brief = brief_res
                        engine.record_tool_result(task.task_id, brief_res.to_tool_result())
                        engine.add_artifact(
                            Artifact(
                                artifact_id=brief_res.brief_id,
                                artifact_type="company_brief",
                                name=f"Brief: {brief_res.company_name}",
                                content=brief_res.summary,
                            )
                        )
                        engine.transition_task(task.task_id, TaskStatus.COMPLETED)
                        if task.retry_count > 0:
                            engine.add_audit_event(
                                event_type="task_retry_succeeded",
                                details={"task_id": task.task_id, "tool": task.tool_name, "retries": task.retry_count},
                            )
                        break

                    elif task.tool_name == "create_onboarding_checklist":
                        checklist_res = create_onboarding_checklist(
                            company_name=last_brief.company_name if last_brief else "Acme Corporation",
                            brief=last_brief,
                        )
                        engine.record_tool_result(task.task_id, checklist_res.to_tool_result())
                        engine.add_artifact(
                            Artifact(
                                artifact_id=checklist_res.checklist_id,
                                artifact_type="onboarding_checklist",
                                name="Onboarding Checklist",
                                content=f"{len(checklist_res.items)} items generated",
                            )
                        )
                        engine.transition_task(task.task_id, TaskStatus.COMPLETED)
                        if task.retry_count > 0:
                            engine.add_audit_event(
                                event_type="task_retry_succeeded",
                                details={"task_id": task.task_id, "tool": task.tool_name, "retries": task.retry_count},
                            )
                        break

                    elif task.tool_name == "draft_welcome_email":
                        email_res = draft_welcome_email(
                            company_name=last_brief.company_name if last_brief else "Acme Corporation",
                            brief=last_brief,
                        )
                        engine.record_tool_result(task.task_id, email_res.to_tool_result())
                        engine.add_artifact(
                            Artifact(
                                artifact_id=email_res.draft_id,
                                artifact_type="welcome_email_draft",
                                name="Welcome Email Draft",
                                content=email_res.body,
                            )
                        )
                        engine.transition_task(task.task_id, TaskStatus.COMPLETED)
                        if task.retry_count > 0:
                            engine.add_audit_event(
                                event_type="task_retry_succeeded",
                                details={"task_id": task.task_id, "tool": task.tool_name, "retries": task.retry_count},
                            )
                        engine.request_approval(
                            action=f"Dispatch Welcome Email for {email_res.recipient}",
                            task_id=task.task_id,
                        )
                        break

                except Exception as exc:
                    category, is_retryable = classify_failure(exc)
                    engine.add_audit_event(
                        event_type="failure_classified",
                        details={
                            "task_id": task.task_id,
                            "category": category.value,
                            "is_retryable": is_retryable,
                            "error": str(exc),
                        },
                    )

                    err = ErrorRecord(
                        task_id=task.task_id,
                        error_type=category.value,
                        message=str(exc),
                        retryable=is_retryable,
                    )
                    engine.record_error(err)

                    if retry_policy.should_retry(category, task.retry_count):
                        engine.transition_task(task.task_id, TaskStatus.RETRYING)
                        engine.add_audit_event(
                            event_type="task_retrying",
                            details={
                                "task_id": task.task_id,
                                "retry_count": task.retry_count,
                                "max_retries": retry_policy.max_retries,
                            },
                        )
                        current_attempt += 1
                        continue
                    else:
                        if category == FailureCategory.TRANSIENT and task.retry_count >= retry_policy.max_retries:
                            engine.add_audit_event(
                                event_type="task_retry_exhausted",
                                details={"task_id": task.task_id, "retry_count": task.retry_count},
                            )
                        engine.transition_task(task.task_id, TaskStatus.FAILED)
                        engine.add_audit_event(
                            event_type="task_failed",
                            details={"task_id": task.task_id, "tool": task.tool_name, "error": str(exc)},
                        )
                        # Block downstream dependent tasks
                        engine.block_dependent_tasks(task.task_id)
                        break

        # Determine final workflow status
        final_status = engine.evaluate_final_status()
        if final_status != state.status:
            engine.transition_to(final_status)
            if final_status == WorkflowStatus.COMPLETED:
                engine.add_audit_event(event_type="workflow_completed", details={})
            elif final_status == WorkflowStatus.PARTIALLY_COMPLETED:
                engine.add_audit_event(
                    event_type="workflow_partially_completed",
                    details={
                        "completed_tasks": [t.task_id for t in state.tasks if t.status == TaskStatus.COMPLETED],
                        "failed_tasks": [t.task_id for t in state.tasks if t.status == TaskStatus.FAILED],
                        "blocked_tasks": [t.task_id for t in state.tasks if t.status == TaskStatus.BLOCKED],
                    },
                )
            elif final_status == WorkflowStatus.FAILED:
                engine.add_audit_event(event_type="workflow_failed", details={})

        return state


def create_operations_agent(
    settings: Optional[ModelSettings] = None,
    sdk_agent: Optional[Agent] = None,
    model: Optional[Any] = None,
) -> OperationsAgent:
    """Factory function to build an OperationsAgent instance."""
    return OperationsAgent(settings=settings, sdk_agent=sdk_agent, model=model)
