"""Workflow orchestration, state management, and validation package."""

from app.workflow.state import (
    Approval,
    ApprovalStatus,
    Artifact,
    ErrorRecord,
    Plan,
    StepStatus,
    Task,
    TaskStatus,
    ToolResult,
    WorkflowState,
    WorkflowStatus,
)
from app.workflow.engine import WorkflowEngine
from app.workflow.validation import (
    InvalidTaskTransitionError,
    InvalidWorkflowTransitionError,
    TaskCompletionValidationError,
    TaskExecutionValidationError,
    TaskFieldValidationError,
    ToolResultValidationError,
    ValidationResult,
    WorkflowValidationError,
    ensure_task_completion_valid,
    ensure_task_execution_valid,
    ensure_valid_task_fields,
    ensure_valid_task_transition,
    ensure_valid_tool_result,
    ensure_valid_workflow_transition,
    validate_task_completion,
    validate_task_execution,
    validate_task_fields,
    validate_task_transition,
    validate_tool_result,
    validate_workflow_transition,
)
from app.workflow.recovery import (
    FailureCategory,
    FailureInjector,
    NotFoundFailureError,
    OperationsWorkflowError,
    PermissionFailureError,
    RetryPolicy,
    TransientFailureError,
    ValidationFailureError,
    classify_failure,
    failure_injector,
)

__all__ = [
    "FailureCategory",
    "classify_failure",
    "RetryPolicy",
    "FailureInjector",
    "failure_injector",
    "OperationsWorkflowError",
    "TransientFailureError",
    "ValidationFailureError",
    "NotFoundFailureError",
    "PermissionFailureError",

    "Approval",
    "ApprovalStatus",
    "Artifact",
    "ErrorRecord",
    "Plan",
    "StepStatus",
    "Task",
    "TaskStatus",
    "ToolResult",
    "WorkflowState",
    "WorkflowStatus",
    "WorkflowEngine",
    "WorkflowValidationError",
    "InvalidWorkflowTransitionError",
    "InvalidTaskTransitionError",
    "TaskExecutionValidationError",
    "TaskCompletionValidationError",
    "ToolResultValidationError",
    "TaskFieldValidationError",
    "ValidationResult",
    "validate_workflow_transition",
    "ensure_valid_workflow_transition",
    "validate_task_transition",
    "ensure_valid_task_transition",
    "validate_task_fields",
    "ensure_valid_task_fields",
    "validate_tool_result",
    "ensure_valid_tool_result",
    "validate_task_execution",
    "ensure_task_execution_valid",
    "validate_task_completion",
    "ensure_task_completion_valid",
]
